---
- name: Configuring filebeat
  template:
    src: "{{ item }}.j2"
    dest: /etc/filebeat/{{ item }}
    owner: root
    group: root
    mode: 0600
    backup: yes
  loop:
    - filebeat.yml
  notify: restart filebeat

- name: Shutdown all filebeat modules
  raw: rm -f /etc/filebeat/modules.d/*.yml
  notify: restart filebeat

- name: Configuring modules
  template:
    src: "{{ item }}.j2"
    dest: /etc/filebeat/modules.d/{{ item }}
    owner: root
    group: root
    mode: 0640
  loop: "{{ modules_list }}"
  when: modules_list is defined
  notify: restart filebeat
