---
- name: install filebeat
  package:
    name:
      - filebeat
    state: present

- name: Include configuring filebeat.service
  include_tasks: configuring_filebeat.yml
- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Include start filebeat.service
  include_tasks: start_filebeat.yml
