---
- name: install kibana
  package:
    name:
      - kibana
    state: present

- name : Include configuring kibana.service
  include_tasks: configuring_kibana.yml
- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Include start kibana.service 
  include_tasks: start_kibana.yml
