---
- name: restart kibana
  service: 
    name: kibana 
    state: restarted
- name: check restarting 
  wait_for:
    host: "{{ server_host }}"
    port: "{{ server_port }}"
#        state: started
